[package]
name = "bitdeck"
version = "0.1.2"
edition = "2024"
rust-version = "1.97"
description = "A minimal, fast, deterministic bitmask deck of cards."
repository = "https://codeberg.org/izarma/bitdeck"
license = "MIT OR Apache-2.0"
keywords = ["deck", "cards", "rng", "gamedev", "bitmask"]
categories = ["game-development"]
readme = "README.md"

[features]
default = []
serde = ["dep:serde"]
bevy = ["dep:bevy_ecs"]

[dependencies]
rand = "0.10.2"
serde = { version = "1.0", optional = true, features = ["derive"] }
bevy_ecs = { version = "0.19.0", optional = true, default-features = false }

[dev-dependencies]
ron = "0.12.2"

[package.metadata.docs.rs]
all-features = true
