[package]
name = "bitdeck"
version = "0.2.0"
edition = "2024"
rust-version = "1.97"
description = "64-bit Bitmask with subset mappings."
repository = "https://codeberg.org/izarma/bitdeck"
license = "MIT OR Apache-2.0"
keywords = ["deck", "cards", "rng", "gamedev", "bitmask"]
categories = ["game-development"]
readme = "README.md"

[features]
default = ["rand", "alloc"]
rand = ["dep:rand"]
alloc = ["rand"] # *_into helpers need rand because they build on draw/peek
serde = ["dep:serde"]
bevy = ["dep:bevy_ecs", "dep:bevy_reflect"]
cards = []

[dependencies]
rand = { version = "0.10.2", optional = true, default-features = false }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }
bevy_ecs = { version = "0.19.0", optional = true, default-features = false , features = ["bevy_reflect"] }
bevy_reflect = { version = "0.19.0", optional = true, default-features = false }

[dev-dependencies]
ron = "0.12.2"
bevy_app = "0.19.0"

[[example]]
name = "cards"
required-features = ["cards", "rand", "alloc"]

[[example]]
name = "peek"
required-features = ["cards", "rand", "alloc"]

[[example]]
name = "weighted"
required-features = ["rand"]

[[example]]
name = "bevy"
required-features = ["bevy", "cards", "rand"]

[package.metadata.docs.rs]
all-features = true
